# Generated by Django 3.1.2 on 2020-10-01 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=60)),
                ('prenom', models.CharField(max_length=60)),
                ('telephone', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=60)),
                ('date', models.DateField()),
                ('specialite', models.CharField(max_length=60)),
                ('langue', models.CharField(max_length=60)),
                ('centre', models.CharField(max_length=60)),
            ],
        ),
    ]
