# Generated by Django 3.1.2 on 2020-10-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_medecin'),
    ]

    operations = [
        migrations.AddField(
            model_name='medecin',
            name='password',
            field=models.CharField(default='test', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='password',
            field=models.CharField(default='test', max_length=60),
            preserve_default=False,
        ),
    ]
